version: "3.3"
services:
  rabbitmq_for_webservers_bech:
    image: rabbitmq:3.11.5-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: webservers_bench
    ports:
      - "15672:15672"
      - "5672:5672"
  pg_for_bech:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=webservers_bench
    ports:
      - "15432:5432"
