version: "3.3"
services:
  pg_for_bech:
    image: postgres:15.1
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=webservers_bench
    ports:
      - "15432:5432"
  mysql_for_bech:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: webservers_bench
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  redis_for_bech:
    image: redis:7
    restart: always
    ports:
      - "26379:6379"
