name = "axum"
language = "rust"

[run_options]
[run_options.async]
BUILD_COMMAND = "cargo build --release"
RUN_COMMAND = "cargo run --manifest-path web_servers/rs_axum/Cargo.toml --release > /dev/null"
database = "postgres"
db_client = "deadpool-postgres"