name = "fastapi"
language = "python"

[run_options]
[run_options.postgres_raw]
BUILD_COMMAND = "python3.11 -m venv venv && source ./venv/bin/activate && pip install -r requirements.txt"
RUN_COMMAND = "PYTHONPATH=./web_servers/py_fast_api DATABASE=postgres_raw ./web_servers/py_fast_api/venv/bin/uvicorn src.main:app --workers 8 > /dev/null"
database = "postgres"
orm = false

[run_options.postgres_alchemy]
BUILD_COMMAND = "python3.11 -m venv venv && source ./venv/bin/activate && pip install -r requirements.txt"
RUN_COMMAND = "PYTHONPATH=./web_servers/py_fast_api DATABASE=postgres_alchemy ./web_servers/py_fast_api/venv/bin/uvicorn src.main:app --workers 8 > /dev/null"
database = "postgres"
orm = true

[run_options.mysql_raw]
BUILD_COMMAND = "python3.11 -m venv venv && source ./venv/bin/activate && pip install -r requirements.txt"
RUN_COMMAND = "PYTHONPATH=./web_servers/py_fast_api DATABASE=mysql_raw ./web_servers/py_fast_api/venv/bin/uvicorn src.main:app --workers 8 > /dev/null"
database = "mysql"
orm = false

[run_options.mysql_alchemy]
BUILD_COMMAND = "python3.11 -m venv venv && source ./venv/bin/activate && pip install -r requirements.txt"
RUN_COMMAND = "PYTHONPATH=./web_servers/py_fast_api DATABASE=mysql_alchemy ./web_servers/py_fast_api/venv/bin/uvicorn src.main:app --workers 8 > /dev/null"
database = "mysql"
orm = true
