name = "gin"
language = "go"

[run_options]
[run_options.postgres_raw]
BUILD_COMMAND = "GIN_MODE=release go build main.go"
RUN_COMMAND = "cd ./web_servers/go_gin/ && GIN_MODE=release go run main.go > /dev/null"
database = "postgres"
db_client = "pgx/v5"