name = "fasthttp"
language = "go"

[run_options]
[run_options.postgres_raw]
BUILD_COMMAND = "go build main.go"
RUN_COMMAND = "cd ./web_servers/go_fasthttp/ && DATABASE=postgres_raw go run main.go > /dev/null"
database = "postgres"
db_client = "pgx/v5"

[run_options.mysql_raw]
BUILD_COMMAND = "go build main.go"
RUN_COMMAND = "cd ./web_servers/go_fasthttp/ && DATABASE=mysql_raw go run main.go > /dev/null"
database = "mysql"
db_client = "go-sql-driver"


[run_options.redis]
BUILD_COMMAND = "go build main.go"
RUN_COMMAND = "cd ./web_servers/go_fasthttp/ && DATABASE=redis go run main.go > /dev/null"
database = "mysql"
db_client = "go-redis"