name = "actix-web"
language = "rust"

[run_options]
[run_options.postgres_raw]
BUILD_COMMAND = "cargo build --release"
RUN_COMMAND = "cargo run --manifest-path web_servers/rs_actixweb/Cargo.toml --release > /dev/null"
database = "postgres"
db_client = "deadpool-postgres"